import { useEffect, useMemo, useState, useCallback } from "react";
import { useNavigate } from "react-router-dom";
import styles from "../styles/HowItWorks.module.css";
import { Button } from "../ui/Button";

const API_LIST = [
  { key: "osrm", name: "OSRM (Routing Engine)", desc: "Computes travel distances and durations based on real road network data for route ordering and geometry generation.", href: "https://project-osrm.org/docs/v5.24.0/api/" },
  { key: "leaflet", name: "Leaflet", desc: "Interactive map rendering library used for route visualization and POI marker display.", href: "https://leafletjs.com" },
  { key: "osm", name: "OpenStreetMap", desc: "Primary backbone for geographic data, providing coordinates and baseline POI entries through the Overpass API.", href: "https://www.openstreetmap.org/copyright" },
  { key: "wikipedia", name: "Wikipedia / Wikidata", desc: "Used to identify culturally significant locations and retrieve descriptive content for POI enrichment.", href: "https://www.mediawiki.org/wiki/API:REST_API" },
  { key: "google-places", name: "Google Places API", desc: "Enriches POIs with popularity attributes (rating, review counts) and retrieves candidate photographs for visual content.", href: "https://developers.google.com/maps/documentation/places" },
  { key: "google-tts", name: "Google Text-to-Speech", desc: "Generates multilingual audio guides (TR, EN, DE) from refined textual descriptions for POI narration.", href: "https://cloud.google.com/text-to-speech" },
  { key: "claude", name: "Claude Haiku (Anthropic)", desc: "Lightweight LLM used for text refinement, paraphrasing, and multilingual translation of POI descriptions during dataset preparation.", href: "https://www.anthropic.com/claude" },
];

const TEAM = [
  { name: "Ebrar Sude Doğan", role: "Project Manager", photoUrl: "/us/ebrar_sude_dogan.jpeg" },
  { name: "Erdem Baran", role: "Database Administrator & API Specialist", photoUrl: "/us/erdem_baran.jpeg" },
  { name: "Kayrahan Toprak Tosun", role: "Scrum Master & Backend Development Leader", photoUrl: "/us/kayrahan_toprak_tosun.jpeg" },
  { name: "Tuna Kodal", role: "Route Algorithm, Backend & Frontend Developer", photoUrl: "/us/tuna_kodal.jpeg" },
];

const FLOW = [
  { key: "input", title: "User Planning Input", text: "User selects destination city, trip duration, daily distance constraints, and preferred interest categories. These define the feasibility bounds and candidate POI pool." },
  { key: "validate", title: "Feasibility Validation", text: "System evaluates the requested configuration against available POIs. If insufficient, it suggests an alternative number of days or prompts category revision." },
  { key: "filter", title: "Database Retrieval & Filtering", text: "Backend retrieves POIs from PostgreSQL (via Supabase) for the selected city, then applies category-based filtering and basic constraints." },
  { key: "candidate", title: "Monte Carlo Candidate Generation", text: "For each day, 500+ candidate routes are generated by randomly sampling 4–9 POIs from the pool. Routes exceeding the 7-hour daily limit are discarded." },
  { key: "score", title: "Composite Scoring & Selection", text: "Candidates are evaluated using a weighted score combining distance fit (Gaussian), spatial variance, popularity, category diversity, and POI count. The highest-scoring feasible route is selected." },
  { key: "order", title: "Route Ordering (Nearest-Neighbor)", text: "Selected POIs are ordered using a greedy nearest-neighbor heuristic starting from the centroid-farthest point, then sent to OSRM for real road geometry." },
  { key: "assemble", title: "Day-by-Day Itinerary Assembly", text: "Selected POIs are removed from the pool, and the process repeats for subsequent days until the trip duration is satisfied." },
  { key: "viz", title: "Frontend Route Visualization", text: "Map renders markers and OSRM polylines via Leaflet. Users explore POIs through the interactive map and ordered stop list." },
  { key: "replan", title: "Interactive Replanning", text: "Users can add, delete, or reorder POIs. Modified days are sent to the backend, which recomputes OSRM routes and returns updated geometry." },
  { key: "explore", title: "POI Exploration & Audio Guides", text: "POI detail pages provide curated images, multilingual descriptions, and audio narration generated via Google TTS in Turkish, English, and German." },
];

export default function HowItWorks() {
  const navigate = useNavigate();

  const [rows, setRows] = useState([]);
  const [loading, setLoading] = useState(false);
  const [err, setErr] = useState(null);

  const refreshRandom = useCallback(async () => {
    setLoading(true);
    setErr(null);
    try {
      const res = await fetch("/api/v1/pois/random?limit=20");
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = await res.json();
      setRows(Array.isArray(data?.items) ? data.items : []);
    } catch (e) {
      setErr(e?.message ?? "Failed to load");
      setRows([]);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    refreshRandom();
  }, [refreshRandom]);

  const tableMeta = useMemo(() => {
    if (loading) return "Loading random samples…";
    if (err) return `Backend error: ${err}`;
    return `Showing ${rows.length} random POIs from a dataset of 2,337 locations across all 81 provinces of Türkiye.`;
  }, [loading, err, rows.length]);

  return (
    <div className={styles.page}>
      <div className={styles.hero}>
        <header className={styles.header}>
          <h2 className={styles.title}>
            How <span className={styles.brand}>GUIDE</span> Works
          </h2>
          <p className={styles.subtitle}>
            GUIDE transforms user-defined travel preferences into structured, route-aware multi-day itineraries
            by combining curated POI data, Monte Carlo-based heuristic optimization, and real road network routing.
          </p>
        </header>

        {/* DB Overview */}
        <section className={styles.section}>
          <div className={styles.sectionTitle}>Point of Interest Database</div>

          <div className={styles.tableWrap}>
            <div className={styles.tableTopRow}>
              <div className={styles.tableMeta}>{tableMeta}</div>

              <button
                type="button"
                className={styles.tableAction}
                onClick={refreshRandom}
                disabled={loading}
              >
                {loading ? "Refreshing..." : "Random Refresh"}
              </button>
            </div>

            <div className={styles.tableScroll}>
              <table className={styles.table}>
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>City</th>
                    <th>Main Category</th>
                    <th>Subcategory</th>
                    <th>Rating</th>
                    <th>Reviews</th>
                    <th>Lat</th>
                    <th>Lng</th>
                  </tr>
                </thead>
                <tbody>
                  {!loading && rows.length === 0 && (
                    <tr>
                      <td colSpan="9" style={{ textAlign: "center", padding: 20 }}>
                        No data available
                      </td>
                    </tr>
                  )}

                  {rows.map((r) => (
                    <tr key={r.id}>
                      <td className={styles.mono}>{r.id}</td>
                      <td className={styles.strongCell}>{r.name}</td>
                      <td>{r.city}</td>
                      <td>{r.main_category_1}</td>
                      <td>{r.sub_category_1}</td>
                      <td>{r.google_rating?.toFixed?.(1) ?? "—"}</td>
                      <td>{r.google_reviews_total ?? "—"}</td>
                      <td className={styles.mono}>
                        {typeof r.lat === "number" ? r.lat.toFixed(4) : "—"}
                      </td>
                      <td className={styles.mono}>
                        {typeof r.lng === "number" ? r.lng.toFixed(4) : "—"}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </section>

        {/* System Flow */}
        <section className={styles.section}>
          <div className={styles.sectionTitle}>System Flow</div>

          <div className={styles.flowGrid}>
            {FLOW.map(({ key, title, text }, idx) => (
              <div key={key} className={styles.flowCard}>
                <div className={styles.flowNum}>{idx + 1}</div>
                <div className={styles.flowTitle}>{title}</div>
                <div className={styles.flowText}>{text}</div>
              </div>
            ))}
          </div>
        </section>

        {/* Data Sources */}
        <section className={styles.section}>
          <div className={styles.sectionTitle}>Data Sources & External Services</div>

          <div className={styles.apiGrid}>
            {API_LIST.map(({ key, href, name, desc }) => (
              <a
                key={key}
                href={href}
                target="_blank"
                rel="noopener noreferrer"
                className={styles.apiCard}
              >
                <div className={styles.apiName}>{name}</div>
                <div className={styles.apiDesc}>{desc}</div>
              </a>
            ))}
          </div>
        </section>

        {/* Team */}
        <section className={styles.section}>
          <div className={styles.teamTitle}>
            Meet the team behind <span className={styles.teamAccent}>GUIDE</span>
          </div>

          <div className={styles.teamGrid}>
            {TEAM.map((m) => (
              <div key={m.name} className={styles.memberCard}>
                <div className={styles.avatar}>
                  {m.photoUrl ? (
                    <img className={styles.avatarImg} src={m.photoUrl} alt={m.name} />
                  ) : (
                    <div className={styles.avatarPh} aria-hidden="true" />
                  )}
                </div>
                <div className={styles.memberName}>{m.name}</div>
                <div className={styles.memberRole}>{m.role}</div>
              </div>
            ))}
          </div>
        </section>

        <div className={styles.bottomRow}>
          <Button variant="ghost" className={styles.backBtnBottom} onClick={() => navigate("/")}>
            Back to landing
          </Button>
        </div>
      </div>
    </div>
  );
}